// GENERATED by scripts/measure-tile-sheet.mjs — do not edit by hand.
//
// Pixel rectangles of each face in public/assets/tiles/mahjong-tiles-sheet.png,
// detected rather than eyeballed so a re-exported sheet is one command to re-measure
// (npm run measure:tiles). The 8 elvis-* entries currently point at the sheet's
// flowers and seasons; milestone 08 replaces them with photographs.

export const SHEET_SIZE = {"width":1024,"height":1024};

export const BORDER_CELL = {"x":6,"y":120,"w":44,"h":480};

export const FACE_CELLS = {
  "dot-1": {
    "x": 82,
    "y": 175,
    "w": 79,
    "h": 98
  },
  "dot-2": {
    "x": 179,
    "y": 175,
    "w": 79,
    "h": 98
  },
  "dot-3": {
    "x": 276,
    "y": 175,
    "w": 78,
    "h": 98
  },
  "dot-4": {
    "x": 375,
    "y": 175,
    "w": 78,
    "h": 98
  },
  "dot-5": {
    "x": 472,
    "y": 175,
    "w": 78,
    "h": 98
  },
  "dot-6": {
    "x": 568,
    "y": 175,
    "w": 78,
    "h": 98
  },
  "dot-7": {
    "x": 663,
    "y": 175,
    "w": 78,
    "h": 98
  },
  "dot-8": {
    "x": 760,
    "y": 175,
    "w": 78,
    "h": 98
  },
  "dot-9": {
    "x": 857,
    "y": 175,
    "w": 79,
    "h": 98
  },
  "bamboo-1": {
    "x": 82,
    "y": 329,
    "w": 79,
    "h": 98
  },
  "bamboo-2": {
    "x": 179,
    "y": 329,
    "w": 78,
    "h": 98
  },
  "bamboo-3": {
    "x": 276,
    "y": 329,
    "w": 78,
    "h": 98
  },
  "bamboo-4": {
    "x": 373,
    "y": 329,
    "w": 78,
    "h": 98
  },
  "bamboo-5": {
    "x": 470,
    "y": 329,
    "w": 78,
    "h": 98
  },
  "bamboo-6": {
    "x": 567,
    "y": 329,
    "w": 78,
    "h": 98
  },
  "bamboo-7": {
    "x": 664,
    "y": 329,
    "w": 78,
    "h": 98
  },
  "bamboo-8": {
    "x": 761,
    "y": 329,
    "w": 78,
    "h": 98
  },
  "bamboo-9": {
    "x": 857,
    "y": 329,
    "w": 79,
    "h": 98
  },
  "character-1": {
    "x": 82,
    "y": 488,
    "w": 79,
    "h": 98
  },
  "character-2": {
    "x": 179,
    "y": 488,
    "w": 78,
    "h": 98
  },
  "character-3": {
    "x": 276,
    "y": 488,
    "w": 78,
    "h": 98
  },
  "character-4": {
    "x": 373,
    "y": 488,
    "w": 78,
    "h": 98
  },
  "character-5": {
    "x": 470,
    "y": 488,
    "w": 78,
    "h": 98
  },
  "character-6": {
    "x": 567,
    "y": 488,
    "w": 78,
    "h": 98
  },
  "character-7": {
    "x": 664,
    "y": 488,
    "w": 78,
    "h": 98
  },
  "character-8": {
    "x": 761,
    "y": 488,
    "w": 78,
    "h": 98
  },
  "character-9": {
    "x": 857,
    "y": 488,
    "w": 79,
    "h": 98
  },
  "wind-east": {
    "x": 82,
    "y": 670,
    "w": 79,
    "h": 98
  },
  "wind-south": {
    "x": 179,
    "y": 670,
    "w": 78,
    "h": 98
  },
  "wind-west": {
    "x": 276,
    "y": 670,
    "w": 78,
    "h": 98
  },
  "wind-north": {
    "x": 373,
    "y": 670,
    "w": 78,
    "h": 98
  },
  "dragon-red": {
    "x": 563,
    "y": 670,
    "w": 79,
    "h": 98
  },
  "dragon-green": {
    "x": 660,
    "y": 670,
    "w": 78,
    "h": 98
  },
  "dragon-white": {
    "x": 757,
    "y": 670,
    "w": 78,
    "h": 98
  },
  "elvis-1": {
    "x": 82,
    "y": 843,
    "w": 79,
    "h": 99
  },
  "elvis-2": {
    "x": 179,
    "y": 843,
    "w": 78,
    "h": 99
  },
  "elvis-3": {
    "x": 276,
    "y": 843,
    "w": 78,
    "h": 99
  },
  "elvis-4": {
    "x": 373,
    "y": 843,
    "w": 78,
    "h": 99
  },
  "elvis-5": {
    "x": 567,
    "y": 843,
    "w": 78,
    "h": 99
  },
  "elvis-6": {
    "x": 664,
    "y": 843,
    "w": 78,
    "h": 99
  },
  "elvis-7": {
    "x": 761,
    "y": 843,
    "w": 78,
    "h": 99
  },
  "elvis-8": {
    "x": 857,
    "y": 843,
    "w": 79,
    "h": 99
  }
};
