#!/usr/bin/env node
// Writes dist/sw.js after a build, listing every file in dist so the whole game is
// precached and works with the wifi off. Runs as part of `npm run build`.
//
// Hand-rolled rather than adding a PWA plugin: the entire requirement is "cache these
// 30 files, serve them offline, and update when the build changes", which is a short
// enough service worker to read in one sitting — and it keeps the dependency list at
// three packages.
//
// Every path is written RELATIVE, because the game is served from a GitHub Pages
// project subpath and an absolute path would resolve against the domain root.

import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative, resolve } from 'node:path';
import { createHash } from 'node:crypto';

const DIST = resolve('dist');

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

const files = walk(DIST)
  .map((file) => relative(DIST, file).split('\\').join('/'))
  .filter((file) => file !== 'sw.js')
  .sort();

// The cache name is a hash of the file list plus their contents, so a new build
// always lands in a fresh cache and the old one is dropped. Without this she could be
// stuck on a stale version indefinitely, with no way to force a refresh.
const hash = createHash('sha256');
for (const file of files) hash.update(file).update(readFileSync(join(DIST, file)));
const version = hash.digest('hex').slice(0, 12);

const sw = `// GENERATED by scripts/build-sw.mjs — do not edit by hand.
const CACHE = 'dawns-mahjong-${version}';
const FILES = ${JSON.stringify(['./', ...files], null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(FILES)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  // Drop every older cache: one player, one device, and a half-updated game is worse
  // than a slightly slower first load.
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  // Cache-first. The game is fully static, so the cache is always right for the
  // version it was built from, and it means the tablet opens instantly with no wifi.
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(request)
        .then((response) => {
          if (response.ok && new URL(request.url).origin === self.location.origin) {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy));
          }
          return response;
        })
        .catch(() =>
          // Offline and not cached: for a navigation, fall back to the start page so
          // she never sees the browser's error screen.
          request.mode === 'navigate' ? caches.match('./') : Response.error()
        );
    })
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);
console.log(`sw.js written — cache dawns-mahjong-${version}, ${files.length} files precached`);
